class Locator_Path():
    textbox_username_id = "username1"
    textbox_password_id = "password1"
    Submit_button = "login"
    button_logout_id = "logout"
    cQube_Dashboard = "cQb_dhsbrd"
    logout = "logout"
    BackButton = "backBtn"
    logoutbutton = "logoutBtn"

    # menu_opts
    menu_icon = "menuIcon"
    cQube_logo = "cubeLogo"
    Dashboard = "menu"
    sch_infra = "SchInfra"
    std_performance = "stdPerformance"
    attendance = "attendance"
    tpd_opts = "tpd"
    other_diksha = "common"
    diksha_ETB = "etb"
    crc_visit = "crc"
    composite_metrics = "composite"
    progress_card = "progressCard"
    Exception_Reports = "exceptList"
    Telemetry = "telemetry"

    InfraMap = "imr"
    Hyperlink = "dist"
    Block_button = "blockbtn"
    Cluster_button = "clusterbtn"
    School_button = "schoolbtn"
    Choose_Dist = "choose_dist"
    Choose_Block = "choose_block"
    Choose_Cluster = "choose_cluster"
    Choose_Infra = "choose_infra"
    loader = "loader"
    Downloads = "download1"
    Management = "name"
    markers = "leaflet-interactive"
    hyper_link = "//p/span"
    sc_no_of_schools = "footer"

    Compositereport = "cr"
    d_names = "//th[contains(text(),'district')]"
    x = "xAxis"
    y = "yAxis"

    UdiseReport = "udise"
    schoolcount = "schools"

    SAT = "sat"
    sr_dist_hyper = "//*[@id='block']/span[1]"
    sr_school_hyper = "//*[@id='school']/span[5]"
    sr_cluster_hyper = "//*[@id='cluster']/span[3]"
    Grade = "grades"
    Subject = "subjects"

    Sat_Heat_Chart = "satHeatChart"
    question_id = "question_id_allDistricts_"
    indicator_id = "indicator_allDistricts_"
    view_by = "viewBy"
    grade = "grade"
    exam_dates = "examDate"
    sar_year = "year"
    sar_month = "month"
    subjects = "subject"
    district_dropdown = "district"
    blocks_dropdown = "block"
    cluster_dropdown = "cluster"

    PAT = "pat1"
    PAT_HC = "heatChart"
    year_select = "year"

    PAT_LO = "lotable"